CREATE TABLE event_ancient_nightmare (day VARCHAR(10), time VARCHAR(10), headup TINYINT(1));
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "12:00", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "20:30", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "22:00", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "11:45", 1);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "20:15", 1);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Wednesday", "21:45", 1);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "12:00", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "20:30", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "22:00", 0);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "11:45", 1);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "20:15", 1);
INSERT INTO event_ancient_nightmare (day, time, headup) VALUES ("Friday", "21:45", 1);